{% set name = "mdal-python" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ViRGIS-Team/mdal-python/archive/refs/tags/{{ version }}.tar.gz
  sha256: 6040327ed448f4782a1588bd7b11f3cdc1e4d20f8064b8c4e6cd38ea8d289334

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
 
requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - mdal >0.9.0a1
    - numpy
    - scikit-build
    - pip
    - cython
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - mdal
    - meshio

test:
  commands:
    - python -c "import mdal"

about:
  home: https://www.mdal.xyz
  license: MIT
  license_file: LICENSE
  summary: Mesh Data Abstraction Library (MDAL) Python Integration
  description: |
    Mesh Data Abstraction Library (MDAL) is a C++ library for handling
    unstructured mesh data released with MIT license. It provides a single
    data model for multiple supported data formats. MDAL is used by QGIS
    for data access for mesh layers. This package provides the Python
    integration for MDAL.
  doc_url:  https://virgis-team.github.io/mdal-python/html/index.html
  dev_url: https://github.com/ViRGIS-Team/mdal-python

extra:
  recipe-maintainers:
    - runette
    - PeterPetrik
