{% set name = "mdal-python" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ViRGIS-Team/mdal-python/archive/refs/tags/{{ version }}.tar.gz
  sha256: 2faa2a1b8aedf10440bc7bdb44e14c4db3f9414450b6a30f8941ec83efc81dd4

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
 
requirements:
  build:
    - {{ compiler('cxx') }}
    - make  # [not win]
    - cmake
  host:
    - python
    - mdal
    - numpy
    - scikit-build
    - pip
    - cython
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - mdal
    - meshio

test:
  commands:
    - python -c "import mdal"

about:
  home: https://www.mdal.xyz
  license: MIT
  license_file: LICENSE
  summary: Mesh Data Abstraction Library (MDAL) Python Integration
  description: |
    Mesh Data Abstraction Library (MDAL) is a C++ library for handling
    unstructured mesh data released with MIT license. It provides a single
    data model for multiple supported data formats. MDAL is used by QGIS
    for data access for mesh layers. This package provides the Python
    integration for MDAL.
  doc_url:  https://virgis-team.github.io/mdal-python/html/index.html
  dev_url: https://github.com/ViRGIS-Team/mdal-python

extra:
  recipe-maintainers:
    - runette
    - PeterPetrik
